### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [brycebaril/through2-filter#5]
Would you please consider adding a LICENSE file to your package, which contains your copyright information and the text of the MIT license?  The MIT license specifically requires that the license text itself accompany the source code.  If you do that, it makes it easier for people like me to package up your code for Linux distributions.

**Comment by brycebaril** [comment]
Hi @jaredsmith -- the package has this https://github.com/brycebaril/through2-filter/blob/master/LICENSE

Is that what you were looking for?

**Comment by jaredsmith** [comment]
Yes, I totally missed that.  Thanks!
