### ISSUE TITLE
Breaking changes merged to MASTER, please add a new MAJOR version to avoid affecting current implementations

### ISSUE THREAD

**Issue by alvaroautobits** [brycebaril/through2-filter#8]
Hello @realityking @brycebaril !
The modifications you merged to MASTER last week compromised several legacy apps we have in place using version 3.0.0 of this library.
Please consider releasing a new version (MAJOR release) for this library to avoid affecting current implementations.

<img width="1752" alt="image" src="https://github.com/brycebaril/through2-filter/assets/167623533/02df289a-6857-4168-a610-efe54d7b394b">

_Originally posted by @alvaroautobits in https://github.com/brycebaril/through2-filter/issues/7#issuecomment-2067658517_

**Comment by brycebaril** [comment]
Many apologies, but also please note that those versions of Node are extremely dangerously unsupported and insecure and you should not be using them. I will do the work to undo this mistake of mine.

**Comment by brycebaril** [comment]
Version 3.1.0 has been deprecated and this version has been re-pushed as 4.0.0.

**Comment by alvaroautobits** [comment]
Hello guys!
Thanks for your help 💪 
Unfortunately, our legacy app is still being affected by changes released in version 3.1.0. 😢 
Let me explain, please; [This is the external dependency](https://github.com/eugeneware/unique-stream/blob/master/package.json#L24) we use in our legacy app that imports this library, this external dependency is still installing the version 3.1.0 (even if it is deprecated) 💥 , what you should really have to do to fix this is reverting this changes as a hotfix (3.1.1), later you have to restore the improvements done by @realityking, and finally, publish them in the version 4 (4.0.1, maybe). 
If everything is done properly, your new latest version will be v4.0.1, and apps that are currently installing your library as "^3.0.0" will not be compromised anymore.
![image](https://github.com/brycebaril/through2-filter/assets/167623533/28b20133-6405-46a6-b0a4-ccc90f94e5d0)
![image](https://github.com/brycebaril/through2-filter/assets/167623533/2ff538a8-e2fd-4df3-9176-88d4ff4f62c8)

**Comment by alvaroautobits** [comment]
Hello @brycebaril @realityking .
I opted to add new step in the CICD pipeline to install the last stable version of the library, and everything is working as expected again 😎 .
This workaround will give us more time to complete the upgrade of our app 😃 .
Thank you very much for your help!!
<img width="1808" alt="image" src="https://github.com/brycebaril/through2-filter/assets/167623533/678163b6-a411-44b5-b70e-a2ab5a5b3623">
